# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-25.0.2.10-hotspot

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3

# Mod Properties
mod_version=2.1.1
maven_group=mchorse, ElGatoPro300, seb0lla, Diobede, Fanyel, Mattux, Sirsyp, Redstoniano, Eleeter
archives_base_name=bbs-cml

# Dependencies
fabric_version=0.160.0+26.2
spruceui_version=11.0.0+26.2
lambdynamiclights_api_version=4.12.4+26.2
lambdynamiclights_runtime_version=4.12.4+26.2
